# Generated by Django 4.1.2 on 2022-10-22 19:47

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.png', force_format='PNG', keep_meta=True, null=True, quality=-1, scale=None, size=[512, 512], upload_to='profile_pic'),
        ),
    ]
