# Generated by Django 4.1.2 on 2022-10-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_email_profile_fname_profile_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(to='home.profile'),
        ),
    ]
