# Generated by Django 4.1.2 on 2022-10-23 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
