# Generated by Django 4.1.2 on 2022-10-23 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_userprofile_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_followers',
            field=models.ManyToManyField(blank=True, related_name='users_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_friends',
            field=models.ManyToManyField(blank=True, related_name='users_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
