# Generated by Django 4.1.2 on 2022-10-20 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_alter_profile_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(blank=True, max_length=200)),
                ('device', models.CharField(blank=True, max_length=200)),
                ('login_datetime', models.DateField(auto_now_add=True)),
                ('device_type', models.CharField(blank=True, max_length=200)),
                ('browser', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
