# Generated by Django 4.1.2 on 2022-10-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_loginsessioninfo_active_loginsessioninfo_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginsessioninfo',
            old_name='login_datetime',
            new_name='login_date',
        ),
    ]
