# Generated by Django 4.1.2 on 2022-10-20 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_login_datetime_loginsessioninfo_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsessioninfo',
            name='login_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
