# Generated by Django 4.1.2 on 2022-10-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_loginsessioninfo_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
