# Generated by Django 4.1.2 on 2022-10-20 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=500)),
                ('vendor', models.CharField(choices=[('paypal', 'Paypal'), ('visa', 'Visa')], max_length=400)),
                ('card_number', models.IntegerField(max_length=500)),
                ('cvc', models.IntegerField()),
                ('card_owner', models.CharField(max_length=500)),
                ('billing_address', models.CharField(max_length=600)),
                ('expiry_date', models.DateField()),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
