# Generated by Django 4.1.2 on 2022-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_alter_billingmethod_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmethod',
            name='card_number',
            field=models.IntegerField(),
        ),
    ]
