# Generated by Django 4.1.2 on 2022-10-22 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='media/post_image')),
                ('post_video', models.FileField(blank=True, null=True, upload_to='media/post_video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_likes', models.IntegerField(default=0)),
                ('post_comments', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
