# Generated by Django 4.1.2 on 2022-10-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_video',
            field=models.FileField(blank=True, null=True, upload_to='post_video'),
        ),
    ]
