# Generated by Django 4.1.2 on 2022-10-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_rename_hiddepost_hiddenpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddenpost',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savedpost',
            name='is_saved',
            field=models.BooleanField(default=True),
        ),
    ]
