# Generated by Django 4.1.2 on 2022-10-24 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0005_hiddenpost_is_hidden_savedpost_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='post_likes',
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_angry',
            field=models.ManyToManyField(related_name='angry_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_haha',
            field=models.ManyToManyField(related_name='haha_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_like',
            field=models.ManyToManyField(related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_love',
            field=models.ManyToManyField(related_name='love_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_sad',
            field=models.ManyToManyField(related_name='sad_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_wow',
            field=models.ManyToManyField(related_name='wow_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
