# Generated by Django 4.1.2 on 2022-10-24 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0006_remove_userpost_post_likes_userpost_post_angry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='post_angry',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post_comments',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post_haha',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post_like',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post_love',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post_sad',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post_wow',
        ),
        migrations.AddField(
            model_name='userpost',
            name='snap_message',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='users_reacted',
            field=models.ManyToManyField(related_name='users_reacted_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_slug', models.CharField(max_length=500)),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('haha', 'Haha'), ('sad', 'Sad'), ('wow', 'Wow'), ('angry', 'Angry'), ('none', 'None')], max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacted_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userpost',
            name='reaction',
            field=models.ManyToManyField(related_name='reaction_object_list', to='post_app.postreaction'),
        ),
    ]
