# Generated by Django 4.1.2 on 2022-10-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_remove_userpost_post_angry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='reaction',
        ),
    ]
