# Generated by Django 4.1.2 on 2022-10-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0008_remove_userpost_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='users_reacted',
        ),
    ]
