# Generated by Django 4.1.2 on 2022-10-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0010_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='comment',
            field=models.TextField(default=['ContextDecorator', 'Local', 'NOT_PASSED', 'RemovedInDjango50Warning', '_PYTZ_IMPORTED', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__getattr__', '__loader__', '__name__', '__package__', '__spec__', '_active', '_datetime_ambiguous_or_imaginary', '_get_timezone_name', '_is_pytz_zone', '_pytz_imported', 'activate', 'datetime', 'deactivate', 'functools', 'get_current_timezone', 'get_current_timezone_name', 'get_default_timezone', 'get_default_timezone_name', 'get_fixed_timezone', 'is_aware', 'is_naive', 'localdate', 'localtime', 'make_aware', 'make_naive', 'now', 'override', 'settings', 'sys', 'template_localtime', 'timedelta', 'timezone', 'tzinfo', 'utc', 'warnings', 'zoneinfo']),
            preserve_default=False,
        ),
    ]
